/* Günlük İletişim · 48 yeni ifade. Seviye etiketi: yaklaşık A2. */
add("de","A2","Günlük İletişim","Können Sie das bitte wiederholen?","Bunu lütfen tekrar eder misiniz?","İfade","Entschuldigung, können Sie das bitte wiederholen?","Affedersiniz, bunu lütfen tekrar eder misiniz?");
add("de","A2","Günlük İletişim","Können Sie bitte langsamer sprechen?","Lütfen daha yavaş konuşur musunuz?","İfade","Ich lerne Deutsch. Können Sie bitte langsamer sprechen?","Almanca öğreniyorum. Lütfen daha yavaş konuşur musunuz?");
add("de","A2","Günlük İletişim","Kann ich mit Karte bezahlen?","Kartla ödeyebilir miyim?","İfade","Das macht zehn Euro. Kann ich mit Karte bezahlen?","Toplam on avro. Kartla ödeyebilir miyim?");
add("de","A2","Günlük İletişim","Ich habe eine Reservierung.","Rezervasyonum var.","İfade","Guten Abend, ich habe eine Reservierung.","İyi akşamlar, rezervasyonum var.");
add("de","A2","Günlük İletişim","Wo muss ich umsteigen?","Nerede aktarma yapmalıyım?","İfade","Ich möchte zum Flughafen. Wo muss ich umsteigen?","Havaalanına gitmek istiyorum. Nerede aktarma yapmalıyım?");
add("de","A2","Günlük İletişim","Das WLAN funktioniert nicht.","Wi-Fi çalışmıyor.","İfade","Das WLAN funktioniert nicht. Können Sie mir helfen?","Wi-Fi çalışmıyor. Bana yardım edebilir misiniz?");
add("de","A2","Günlük İletişim","Ich hätte gern einen Termin.","Randevu almak istiyorum.","İfade","Guten Tag, ich hätte gern einen Termin für nächste Woche.","İyi günler, gelecek hafta için randevu almak istiyorum.");
add("en","A2","Günlük İletişim","Could you repeat that, please?","Bunu lütfen tekrar eder misiniz?","İfade","Sorry, could you repeat that, please?","Affedersiniz, bunu lütfen tekrar eder misiniz?");
add("en","A2","Günlük İletişim","Could you speak more slowly, please?","Lütfen daha yavaş konuşur musunuz?","İfade","I am learning English. Could you speak more slowly, please?","İngilizce öğreniyorum. Lütfen daha yavaş konuşur musunuz?");
add("en","A2","Günlük İletişim","I have a reservation.","Rezervasyonum var.","İfade","Good evening. I have a reservation.","İyi akşamlar. Rezervasyonum var.");
add("en","A2","Günlük İletişim","Where do I need to change trains?","Nerede tren değiştirmem gerekiyor?","İfade","I am going to the airport. Where do I need to change trains?","Havaalanına gidiyorum. Nerede tren değiştirmem gerekiyor?");
add("en","A2","Günlük İletişim","The Wi-Fi is not working.","Wi-Fi çalışmıyor.","İfade","The Wi-Fi is not working. Could you help me?","Wi-Fi çalışmıyor. Bana yardım edebilir misiniz?");
add("en","A2","Günlük İletişim","I would like to make an appointment.","Randevu almak istiyorum.","İfade","Hello, I would like to make an appointment for next week.","Merhaba, gelecek hafta için randevu almak istiyorum.");
add("fr","A2","Günlük İletişim","Pouvez-vous répéter, s’il vous plaît ?","Lütfen tekrar eder misiniz?","İfade","Pardon, pouvez-vous répéter, s’il vous plaît ?","Affedersiniz, lütfen tekrar eder misiniz?");
add("fr","A2","Günlük İletişim","Pouvez-vous parler plus lentement ?","Daha yavaş konuşur musunuz?","İfade","J’apprends le français. Pouvez-vous parler plus lentement ?","Fransızca öğreniyorum. Daha yavaş konuşur musunuz?");
add("fr","A2","Günlük İletişim","Puis-je payer par carte ?","Kartla ödeyebilir miyim?","İfade","Cela fait dix euros. Puis-je payer par carte ?","Toplam on avro. Kartla ödeyebilir miyim?");
add("fr","A2","Günlük İletişim","J’ai une réservation.","Rezervasyonum var.","İfade","Bonsoir, j’ai une réservation.","İyi akşamlar, rezervasyonum var.");
add("fr","A2","Günlük İletişim","Où dois-je changer de train ?","Nerede tren değiştirmem gerekiyor?","İfade","Je vais à l’aéroport. Où dois-je changer de train ?","Havaalanına gidiyorum. Nerede tren değiştirmem gerekiyor?");
add("fr","A2","Günlük İletişim","Le Wi-Fi ne fonctionne pas.","Wi-Fi çalışmıyor.","İfade","Le Wi-Fi ne fonctionne pas. Pouvez-vous m’aider ?","Wi-Fi çalışmıyor. Bana yardım edebilir misiniz?");
add("fr","A2","Günlük İletişim","Pouvez-vous m’indiquer le chemin ?","Bana yolu tarif edebilir misiniz?","İfade","Je cherche la gare. Pouvez-vous m’indiquer le chemin ?","Tren istasyonunu arıyorum. Bana yolu tarif edebilir misiniz?");
add("fr","A2","Günlük İletişim","Je voudrais prendre rendez-vous.","Randevu almak istiyorum.","İfade","Bonjour, je voudrais prendre rendez-vous pour la semaine prochaine.","Merhaba, gelecek hafta için randevu almak istiyorum.");
add("es","A2","Günlük İletişim","¿Puede repetirlo, por favor?","Bunu lütfen tekrar eder misiniz?","İfade","Perdone, ¿puede repetirlo, por favor?","Affedersiniz, bunu lütfen tekrar eder misiniz?");
add("es","A2","Günlük İletişim","¿Puede hablar más despacio?","Daha yavaş konuşur musunuz?","İfade","Estoy aprendiendo español. ¿Puede hablar más despacio?","İspanyolca öğreniyorum. Daha yavaş konuşur musunuz?");
add("es","A2","Günlük İletişim","Tengo una reserva.","Rezervasyonum var.","İfade","Buenas noches, tengo una reserva.","İyi akşamlar, rezervasyonum var.");
add("es","A2","Günlük İletişim","¿Dónde tengo que cambiar de tren?","Nerede tren değiştirmem gerekiyor?","İfade","Voy al aeropuerto. ¿Dónde tengo que cambiar de tren?","Havaalanına gidiyorum. Nerede tren değiştirmem gerekiyor?");
add("es","A2","Günlük İletişim","El wifi no funciona.","Wi-Fi çalışmıyor.","İfade","El wifi no funciona. ¿Puede ayudarme?","Wi-Fi çalışmıyor. Bana yardım edebilir misiniz?");
add("es","A2","Günlük İletişim","¿Puede indicarme el camino?","Bana yolu tarif edebilir misiniz?","İfade","Busco la estación. ¿Puede indicarme el camino?","İstasyonu arıyorum. Bana yolu tarif edebilir misiniz?");
add("es","A2","Günlük İletişim","Quisiera pedir una cita.","Randevu almak istiyorum.","İfade","Hola, quisiera pedir una cita para la próxima semana.","Merhaba, gelecek hafta için randevu almak istiyorum.");
add("ru","A2","Günlük İletişim","Повторите, пожалуйста.","Lütfen tekrar edin.","İfade","Извините, повторите, пожалуйста.","Affedersiniz, lütfen tekrar edin.");
add("ru","A2","Günlük İletişim","Говорите медленнее, пожалуйста.","Lütfen daha yavaş konuşun.","İfade","Я учу русский язык. Говорите медленнее, пожалуйста.","Rusça öğreniyorum. Lütfen daha yavaş konuşun.");
add("ru","A2","Günlük İletişim","Можно оплатить картой?","Kartla ödeyebilir miyim?","İfade","С вас десять евро. Можно оплатить картой?","On avro ödemeniz gerekiyor. Kartla ödeyebilir miyim?");
add("ru","A2","Günlük İletişim","У меня есть бронь.","Rezervasyonum var.","İfade","Добрый вечер, у меня есть бронь.","İyi akşamlar, rezervasyonum var.");
add("ru","A2","Günlük İletişim","Где мне нужно сделать пересадку?","Nerede aktarma yapmam gerekiyor?","İfade","Я еду в аэропорт. Где мне нужно сделать пересадку?","Havaalanına gidiyorum. Nerede aktarma yapmam gerekiyor?");
add("ru","A2","Günlük İletişim","Wi-Fi не работает.","Wi-Fi çalışmıyor.","İfade","Wi-Fi не работает. Вы можете мне помочь?","Wi-Fi çalışmıyor. Bana yardım edebilir misiniz?");
add("ru","A2","Günlük İletişim","Как пройти к вокзалу?","Tren istasyonuna nasıl gidilir?","İfade","Скажите, пожалуйста, как пройти к вокзалу?","Lütfen söyler misiniz, tren istasyonuna nasıl gidilir?");
add("ru","A2","Günlük İletişim","Я хочу записаться на приём.","Randevu almak istiyorum.","İfade","Здравствуйте, я хочу записаться на приём на следующую неделю.","Merhaba, gelecek hafta için randevu almak istiyorum.");
add("ar","A2","Günlük İletişim","هل يمكنك إعادة ذلك من فضلك؟","Bunu lütfen tekrar eder misin?","İfade","عفواً، هل يمكنك إعادة ذلك من فضلك؟","Affedersin, bunu lütfen tekrar eder misin?");
add("ar","A2","Günlük İletişim","هل يمكنك التحدث ببطء أكثر؟","Daha yavaş konuşabilir misin?","İfade","أنا أتعلم العربية. هل يمكنك التحدث ببطء أكثر؟","Arapça öğreniyorum. Daha yavaş konuşabilir misin?");
add("ar","A2","Günlük İletişim","لدي حجز.","Rezervasyonum var.","İfade","مساء الخير، لدي حجز.","İyi akşamlar, rezervasyonum var.");
add("ar","A2","Günlük İletişim","أين يجب أن أغيّر القطار؟","Nerede tren değiştirmem gerekiyor?","İfade","أريد الذهاب إلى المطار. أين يجب أن أغيّر القطار؟","Havaalanına gitmek istiyorum. Nerede tren değiştirmem gerekiyor?");
add("ar","A2","Günlük İletişim","شبكة الواي فاي لا تعمل.","Wi-Fi ağı çalışmıyor.","İfade","شبكة الواي فاي لا تعمل. هل يمكنك مساعدتي؟","Wi-Fi ağı çalışmıyor. Bana yardım edebilir misin?");
add("ar","A2","Günlük İletişim","كيف أصل إلى محطة القطار؟","Tren istasyonuna nasıl giderim?","İfade","عفواً، كيف أصل إلى محطة القطار؟","Affedersiniz, tren istasyonuna nasıl giderim?");
add("ar","A2","Günlük İletişim","أريد حجز موعد.","Randevu almak istiyorum.","İfade","مرحباً، أريد حجز موعد للأسبوع القادم.","Merhaba, gelecek hafta için randevu almak istiyorum.");
add("de","A2","Günlük İletişim","Können Sie mir die Adresse aufschreiben?","Adresi benim için yazar mısınız?","İfade","Ich kenne den Ort nicht. Können Sie mir die Adresse aufschreiben?","Yeri bilmiyorum. Adresi benim için yazar mısınız?");
add("en","A2","Günlük İletişim","Could you write down the address?","Adresi yazar mısınız?","İfade","I do not know the place. Could you write down the address?","Yeri bilmiyorum. Adresi yazar mısınız?");
add("en","A2","Günlük İletişim","Does this train stop at the airport?","Bu tren havaalanında duruyor mu?","İfade","Excuse me, does this train stop at the airport?","Affedersiniz, bu tren havaalanında duruyor mu?");
add("es","A2","Günlük İletişim","¿Puede escribir la dirección?","Adresi yazar mısınız?","İfade","No conozco el lugar. ¿Puede escribir la dirección?","Yeri bilmiyorum. Adresi yazar mısınız?");
add("ar","A2","Günlük İletişim","هل يمكنك كتابة العنوان؟","Adresi yazabilir misin?","İfade","لا أعرف المكان. هل يمكنك كتابة العنوان؟","Yeri bilmiyorum. Adresi yazabilir misin?");
